export enum EnumMembershipStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  CANCELED = 'CANCELED',
  OVERDUE = 'OVERDUE',
}

// NEW_SUBSCRIPTION
// UP_TO_DATE
// SETTLED
// OVERDUE
// CANCELED
// PAST_DUE
// EXPIRED
// RENEWED
// DELAYED
// REVERSED
// TO_START
